name: DailyWave

options:
  bundleIdPrefix: com.dailywave
  deploymentTarget:
    iOS: "17.0"

settings:
  base:
    DEVELOPMENT_TEAM: ""
    SWIFT_VERSION: "5.10"
    PRODUCT_BUNDLE_IDENTIFIER: com.dailywave.iphone
    TARGETED_DEVICE_FAMILY: "1"
    ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon

packages:
  Supabase:
    url: https://github.com/supabase/supabase-swift.git
    from: 2.0.0

targets:
  DailyWave:
    type: application
    platform: iOS
    sources:
      - path: DailyWaveApp/Sources
    resources:
      - path: DailyWaveApp/Resources
    entitlements:
      path: DailyWaveApp/DailyWave.entitlements
    info:
      path: DailyWaveApp/Info.plist
      properties:
        CFBundleDisplayName: DailyWave
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
    dependencies:
      - package: Supabase
        product: Supabase
